
CREATE TABLE ONE_TIME_TOKEN(
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  TOKEN_KEY   VARCHAR(128)  NOT NULL,
  TOKEN       VARCHAR(128)  NOT NULL,
  DATA        TEXT          NOT NULL,
  CREATE_DATE DATETIME      NOT NULL,
  VALID_UNTIL DATETIME      NOT NULL,
  USE_DATE    DATETIME      NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX ONE_TIME_TOKEN_IDX1 ON ONE_TIME_TOKEN(TOKEN_KEY, TOKEN);
